# Generated by Django 3.2.8 on 2021-12-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20211208_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='vendor',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
