# Generated by Django 3.2.8 on 2021-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_unit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
